[package]
name = "deepforge"
edition = "2024.beta"
license = "MIT"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.61.1" }

[addresses]
deepforge = "0x0"
